version: 2.1
executors:
  node-executor:
    docker:
      - image: circleci/node:14

workflows:
  version: 2
  build-and-deploy:
    jobs:
      - build:
          filters:
            branches:
              only:
                - main
                - master

jobs:
  build:
    executor: node-executor
    environment:
      DB_USER: "postgres"
      DB_HOST: "database-1.cudxeddvnonz.ap-southeast-2.rds.amazonaws.com"
      DB_NAME: "udacity"
      DB_PASSWORD: "postgres"
      DB_PORT: 5432
    steps:
      - checkout

      - restore_cache:
          keys:
            - dependency-cache-{{ checksum "package-lock.json" }}

      - run:
          name: Install dependencies
          command: yarn install

      - save_cache:
          key: dependency-cache-{{ checksum "package-lock.json" }}
          paths:
            - node_modules

      - run:
          name: Build
          command: yarn build
